// Code generated by protoc-gen-gogomsglist.
// DO NOT EDIT!

package fuzztests

type Message interface {
	Reset()
	String() string
	ProtoMessage()
}

var NewFuncs = []func() Message{
	func() Message { return &NinOptNative{} },
	func() Message { return &NinRepNative{} },
	func() Message { return &NinRepPackedNative{} },
	func() Message { return &NinOptStruct{} },
	func() Message { return &NinRepStruct{} },
	func() Message { return &NinNestedStruct{} },
	func() Message { return &Nil{} },
	func() Message { return &NestedDefinition{} },
	func() Message { return &NestedScope{} },
	func() Message { return &NinOptNativeDefault{} },
	func() Message { return &NinOptNative3{} },
	func() Message { return &NinRepNative3{} },
	func() Message { return &NinRepPackedNative3{} },
	func() Message { return &NinOptStruct3{} },
	func() Message { return &NinRepStruct3{} },
	func() Message { return &NinNestedStruct3{} },
	func() Message { return &Nil3{} },
	func() Message { return &NestedDefinition3{} },
	func() Message { return &NestedScope3{} },
}
