// Code generated by protoc-gen-gogopop.
// DO NOT EDIT!

package fuzztests

var popFuncs = []interface{}{
	NewPopulatedNinOptNative,
	NewPopulatedNinRepNative,
	NewPopulatedNinOptStruct,
	NewPopulatedNinRepStruct,
	NewPopulatedNinNestedStruct,
	NewPopulatedNil,
	NewPopulatedNestedDefinition,
	NewPopulatedNestedScope,
	NewPopulatedNinOptNativeDefault,
	NewPopulatedNinOptNative3,
	NewPopulatedNinRepNative3,
	NewPopulatedNinOptStruct3,
	NewPopulatedNinRepStruct3,
	NewPopulatedNinNestedStruct3,
	NewPopulatedNil3,
	NewPopulatedNestedDefinition3,
	NewPopulatedNestedScope3,
}
