package fuzztests

var popFuncs = []interface{}{
	NewPopulatedNinOptNative,
	NewPopulatedNinRepNative,
	NewPopulatedNinRepPackedNative,
	NewPopulatedNinOptStruct,
	NewPopulatedNinRepStruct,
	NewPopulatedNinNestedStruct,
	NewPopulatedNil,
	NewPopulatedNinOptEnum,
	NewPopulatedNinRepEnum,
	NewPopulatedNinOptEnumDefault,
	NewPopulatedMyExtendable,
	NewPopulatedOtherExtenable,
	NewPopulatedNestedDefinition,
	NewPopulatedNestedScope,
	NewPopulatedNinOptNativeDefault,
	NewPopulatedNinOptNative3,
	NewPopulatedNinRepNative3,
	NewPopulatedNinRepPackedNative3,
	NewPopulatedNinOptStruct3,
	NewPopulatedNinRepStruct3,
	NewPopulatedNinNestedStruct3,
	NewPopulatedNil3,
	NewPopulatedNinOptEnum3,
	NewPopulatedNinRepEnum3,
	NewPopulatedNestedDefinition3,
	NewPopulatedNestedScope3,
}
